---
title: "経歴"
output:
  html_document:
    toc: false
    css: site_style.css
---

```{r echo=FALSE}
knitr::asis_output(htmltools::htmlPreserve("
  <div class='block1'>
    <h2 class='news'>学歴
    </h2>
    <p>2008.4-2012.3　同志社大学文学部心理学科</p>
    <p>2012.4-2014.3　同志社大学大学院心理学研究科心理学専攻博士前期課程</p>
    <p>2014.4-2017.3　同志社大学大学院心理学研究科心理学専攻博士後期課程</p>
    <p>2017.3.22　博士号（心理学）（同志社大学）取得</p>

  </div>

"))
```

```{r echo=FALSE}
knitr::asis_output(htmltools::htmlPreserve("
  <div class='block1'>
    <h2 class='news'>職歴
    </h2>
    <p>2012.4-2017.3　同志社大学心理学部TA</p>
    <p>2016.9-2017.3　帝塚山大学心理学部非常勤講師（担当：心理学実験実習）</p>
    <p>2017.1-2017.3　大阪府立大学スクールソーシャルワーク評価支援研究所非常勤研究員</p>
    <p>2017.4-2018.3　福島県立医科大学医学部健康リスクコミュニケーション学講座特別研究員</p>
    <p>2018.4-      　日本学術振興会特別研究員PD</p>

  </div>

"))
```

```{r echo=FALSE}
knitr::asis_output(htmltools::htmlPreserve("
  <div class='block1'>
    <h2 class='news'>学会
    </h2>
    <p>日本心理学会、日本社会心理学会、日本教育心理学会、日本パーソナリティ心理学会、ソーシャルモチベーション研究会、貧困研究会、Society for Personality and Social Psychology</p>

  </div>

"))
```