---
title: "報告"
output:
  html_document:
    toc: false
    css: site_style.css
---

```{r echo=FALSE}
knitr::asis_output(htmltools::htmlPreserve("
  <div class='block1'>
    <h2 class='news'>学術論文
    </h2>
    <p>◎小林智之・及川昌典&ensp;(2018).&ensp;メタステレオタイプと平等主義的な信念が集団間相互作用に及ぼす影響&ensp;心理学研究</p>
    <p>◎小林智之・及川昌典&ensp;(2015).&ensp;メタステレオタイプと集団相互依存観が外集団に対する反応に及ぼす影響&ensp;心理学研究</p>
    <p>◎小林智之&ensp;(2015).&ensp;社会的説得の補償効果――自己効力感形成に対する4つの情報源モデル――&ensp;ソーシャル・モチベーション研究</p>
  </div>

"))
```


```{r echo=FALSE}
knitr::asis_output(htmltools::htmlPreserve("
  <div class='block1'>
    <h2 class='news'>地域アウトリーチ活動
    </h2>
    <p>福島県いわき市の保健師スキルアップ研修会　など</p>
  </div>

"))
```


```{r echo=FALSE}
knitr::asis_output(htmltools::htmlPreserve("
  <div class='block1'>
    <h2 class='news'>国際学会の発表
    </h2>
    <p>　Yoshida, K., Kobayashi, T., Goto, A., Takebayashi, Y., Kumagai, A., Yasui, K., Kuroda, Y., Suenaga, K., Komiya, H., & Murakami, M.&ensp;(2018).&ensp;Improving risk communication skills for public health nurses after the Fukushima disaster.&ensp;The 21st East Asian Forum of Nursing Scholars & 11th International Nursing Conference</p>
    <p>◎Kobayashi, T. & Oikawa, M.&ensp;(2017).&ensp;Tragic encounters of the third kind: How negative meta-stereotype leads to infra-humanization.&ensp;The 18th annual meeting for Society for Personality and Social Psychology</p>
    <p>◎Kobayashi, T. & Oikawa, M.&ensp;(2016).&ensp;Where ignorance is bliss: Effect of intergroup contact on meta-stereotype.&ensp;The 17th annual meeting for Society for Personality and Social Psychology</p>
    <p>◎Kobayashi, T. & Oikawa, M.&ensp;(2015).&ensp;The liberals’ dilemma: Effects of negative meta-stereotypes on intergroup anxiety.&ensp;The 31th International Congress of Psychology</p>
    <p>◎Kobayashi, T. & Oikawa, M.&ensp;(2015).&ensp;Reflecting and deflecting meta-stereotypes: The moderating role of group-interdependence.&ensp;The 16th annual meeting for Society for Personality and Social Psychology</p>
    <p>◎Kobayashi, T.&ensp;(2013).&ensp;Effects of reminders of low status on out-group favoritism.&ensp;The 14th annual meeting for Society for Personality and Social Psychology</p>
    <p>◎Kobayashi, T.&ensp;(2012).&ensp;Meta-stereotype, other-stereotype, and self-stereotype.&ensp;2nd Doshisha-Chung-Ang Symposium of Psychological Science 2012</p>
  </div>

"))
```

```{r echo=FALSE}
knitr::asis_output(htmltools::htmlPreserve("
  <div class='block1'>
    <h2 class='news'>国内学会の発表
    </h2>
    <p>　嵯峨嘉子・山野則子・所道彦・駒田安紀・小林智之&ensp;(2017).&ensp;大阪府 子どもの生活に関する実態調査から見える子どもの貧困&ensp;貧困研究会第10回研究大会&ensp;（口頭）</p>
    <p>◎小林智之&ensp;(2017).&ensp;集団間葛藤におけるネガティブなメタステレオタイプの働き&ensp;日本心理学会第81回大会&ensp;（小講演）</p>
    <p>◎小林智之・及川昌典&ensp;(2015).&ensp;ネガティブなメタステレオタイプが自己肯定感に及ぼす影響&ensp;日本心理学会第79回大会&ensp;（ポスター）</p>
    <p>◎小林智之・及川昌典&ensp;(2014).&ensp;ジェンダーメタステレオタイプのネガティブ性の比較検討&ensp;日本心理学会第78回大会&ensp;（ポスター）</p>
    <p>◎小林智之・及川昌典&ensp;(2013).&ensp;外集団の重要性がネガティブなメタステレオタイプの働きへ及ぼす影響&ensp;日本社会心理学会第54回大会&ensp;（口頭）</p>
    <p>◎小林智之・及川昌典&ensp;(2013).&ensp;メタステレオタイプが集団間相互作用へ及ぼす影響&ensp;日本心理学会第77回大会&ensp;（ポスター）</p>
    <p>◎小林智之・及川昌典&ensp;(2013).&ensp;ステータス差の認識による内外集団びいき発生の検討&ensp;第11回関西動機づけ研究会&ensp;（口頭）</p>
    <p>◎小林智之・及川昌典&ensp;(2012).&ensp;メタステレオタイプ、自己ステレオタイプ、他者ステレオタイプの関係&ensp;日本社会心理学会第53回大会&ensp;（口頭）</p>
    <p>◎小林智之&ensp;(2012).&ensp;集団間ステータス差の認識が内外集団びいきに及ぼす影響&ensp;日本心理学会第76回大会&ensp;（ポスター）</p>
  </div>

"))
```


```{r echo=FALSE}
knitr::asis_output(htmltools::htmlPreserve("
  <div class='block1'>
    <h2 class='news'>報告書
    </h2>
    <p>　大阪府　子どもの生活に関する実態調査き&ensp;大阪府立大学　全38報</p>
   </div>

"))
```